### ISSUE TITLE
Mismatching ReadMe

### ISSUE THREAD

**Issue by ilendemli** [kkonteh97/SwiftOBD2App#2]
Hey!

I just wanted to build and try the app but the ReadMe is misleading. iOS 15.0 is defined as minimum deployment version. `#Preview` is an Xcode 15 and Swift 5.9 feature.

Also I would suggest to add SwiftLint to improve the code style as well as xcodegen for better source control.

I might help you out with that and also would like to add support for the cars I have access to. But Bluetooth and OBD with Swift is new for me so might have to read and figure out stuff on the way.

Just ordered myself an ELM reader.

**Comment by kkonteh97** [comment]
hey I so sorry about that. I copied the readme from a different project and forgot to update that part. I will fix it right away. I was. would love to have you help on this project. I have made some in rows in mapping the ecu and getting the decoder for the rpm properly working. 


Edit: dropped minimum deployments to 15 and the readMe. current in the blecommunication I am filtering by name Carly. you can swap that out for the name of the adapter your get. not currently sure what other method I could use.
 @ilendemli

**Comment by MjCodingCamp** [comment]
I'm not able to run your project, getting SMARTOBD2.xcodeproj cannot be opened because it is missing its project.pbxproj file. I would be helpful for me if you can help here.

**Comment by kkonteh97** [comment]
> I'm not able to run your project, getting SMARTOBD2.xcodeproj cannot be opened because it is missing its project.pbxproj file. I would be helpful for me if you can help here.
I will work on fixing this I am trying to use Xcodegen given me 20 minutes lemme make some changes and you can try again.

**Comment by kkonteh97** [comment]
> I'm not able to run your project, getting SMARTOBD2.xcodeproj cannot be opened because it is missing its project.pbxproj file. I would be helpful for me if you can help here.

hey so I got it working with Xcodegen you can now clone the repo, then in the terminal navigate to the project directory and run the command "xcodegen". should be working at that point if not let me know I tested it a couple times on my end

**Comment by MjCodingCamp** [comment]
> > I'm not able to run your project, getting SMARTOBD2.xcodeproj cannot be opened because it is missing its project.pbxproj file. I would be helpful for me if you can help here.
> 
> hey so I got it working with Xcodegen you can now clone the repo, then in the terminal navigate to the project directory and run the command "xcodegen". should be working at that point if not let me know I tested it a couple times on my end

Yeah, it's working now, sorry for the inconvenience. Actually I'm new to BLE, so how can I connect my OBD2 device?
<img width="1008" alt="Screenshot 2023-10-12 at 3 00 19 PM" src="https://github.com/kkonteh97/SmartOBD2/assets/66344914/4dcd720c-21fd-4e36-80bb-fb28235083c2">

I changed Device Name & Device ID with my device name & ID, is there anything else which i need to change ?
