### ISSUE TITLE
How to connect to different Bluetooth OBD adater (than Carly)

### ISSUE THREAD

**Issue by Jaaap** [kkonteh97/SwiftOBD2App#3]
Hello,

My Bluetooth OBD adapter identifies itself as "OBD BLE".
What can i do to get SmartOBD2 to use it? (Currently when i press the connect button, it starts a spinner and appears to wait forever)

Do i need to change RestoreIdentifierKey, DeviceName, serviceUUID and peripheralUUID in `BleConnection.swift`?

**Comment by kkonteh97** [comment]
Hello RestoreIdentifierKey doesn't need change just the userdevice when I get home today I will implement a scan view to be able to search for and connect to a different ble device.

**Comment by Jaaap** [comment]
That would be awesome. Thank you.

**Comment by kkonteh97** [comment]
> That would be awesome. Thank you.

I have add a list of the devices broadcasting the serve FFE0 because that's the service I think most obd devices communicate. if your device is not showing up change let me know or change         centralManager?.scanForPeripherals(withServices: [CBUUID(string: service)], options: scanOption)
to         centralManager?.scanForPeripherals(withServices: nil, options: scanOption) this will make it it scans for all devices

**Comment by Jaaap** [comment]
Yes i had to use `withServices: nil` before it saw the "OBD BLE".
It has services 1804, Battery and FFF0 (all isPrimary = YES)
I also captured the peripheralUUID.

**Comment by kkonteh97** [comment]
> Yes i had to use `withServices: nil` before it saw the "OBD BLE". It has services 1804, Battery and FFF0 (all isPrimary = YES) I also captured the peripheralUUID.

still trying the figure out how I could be more flexible with the bluetooth adapters but for now change FFE1 to FFF0
guard let characteristics = service.characteristics else {
            logger.error("No characteristics found")
            return
        }
        self.discoveredServicesAndCharacteristics.append((service, characteristics))

        for characteristic in characteristics {
            switch characteristic.uuid.uuidString {
            case "FFE1":
                ecuCharacteristic = characteristic
                peripheral.setNotifyValue(true, for: characteristic)
                logger.info("Adapter Ready")
            default:
                if debug {
                    logger.info("Unhandled Characteristic UUID: \(characteristic.uuid)")
                }
                if characteristic.properties.contains(.notify) {
                    peripheral.setNotifyValue(true, for: characteristic)

                }
            }
        }
